# Server Configurations
server.port=8080

# ==========================================
# MYSQL DATABASE CONFIGURATIONS
# ==========================================
# Replace "root" with your actual MySQL database credentials if they differ.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configurations for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# "update" automatically generates the tables in MySQL when Spring Boot starts up
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# MAIL CONFIGURATIONS
# ==========================================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Custom Portfolio Mail Settings
portfolio.mail.to=${PORTFOLIO_RECEIVER_EMAIL:ompawar7511@gmail.com}
